### ISSUE TITLE
Design: text aligns

### ISSUE THREAD

**Issue by elina2022** [Tristandemuijnck/UltiTV-interaction-functionality#10]
![image](https://user-images.githubusercontent.com/112861148/229465968-f9e6d66e-cd28-4302-8599-cc091ea883c1.png)
Hier zie ik dat in een klein stukje tekst verschillende text aligns worden gebruikt. Het zou er misschien wat rustiger uitzien als je de titel en het paragraaf allebei links zou alignen. Door de border-bottom is het dan nogsteeds duidelijk dat de bovenste regel de titel is.

**Comment by Tristandemuijnck** [comment]
Fixed :)

![image](https://user-images.githubusercontent.com/43402897/229619380-3de3a7b3-6950-4a5f-9678-050055249d88.png)
