### ISSUE TITLE
Design: Information button

### ISSUE THREAD

**Issue by elina2022** [Tristandemuijnck/UltiTV-interaction-functionality#11]
Als ik op de information button hover blijft de cursor op default staan. Dit zorgt ervoor dat het niet meteen duidelijk is dat dit klikbaar is. Ik zie dat er een kleine wijziging in de kleur is wat wel al mooi is, een extra poiner als cursor zou dit nog helderder maken.

**Comment by Tristandemuijnck** [comment]
Pointer toegevoegd on hover.
