### ISSUE TITLE
Design: Padding & witruimte

### ISSUE THREAD

**Issue by elina2022** [Tristandemuijnck/UltiTV-interaction-functionality#12]
![image](https://user-images.githubusercontent.com/112861148/229470019-9d6e3818-5b87-4411-a146-d9f52b202606.png)
Ik zie hier dat op een breed scherm weinig padding is voor het witte achtergrond vlak. Aangezien er ook best veel witruimte is tussen de naam van de speler en de stats geeft dat je een kans om de padding wat meer te maken zonder dat alles te dicht op elkaar komt.

**Comment by Tristandemuijnck** [comment]
Padding naar 1em gezet & player cards min-height verwijderd. 

![image](https://user-images.githubusercontent.com/43402897/229614703-08059bd5-e0c2-47b7-b977-df5e247ead01.png)
